### ISSUE TITLE
New command line option to start in auto-refresh mode

### ISSUE THREAD

**Issue by gtrianta1965** [gtrianta1965/ServiceWatcher#12]
Introduce a new command line switch -autorefresh that instruct the program to start in auto refresh mode. The interval can be specified as a second argument e.g. -autorefresh 30

This means that the autorefresh interval should be one of the values of autoRefreshInterval configuration parameters (or is this not necessary)

**Comment by androklis** [comment]
In case we need autoRefreshInterval include the value from command line we can simply call the method setAutoRefreshIntervals() and add ttat value

**Comment by KALALEX** [comment]
ready to merge

**Comment by androklis** [comment]
Provided on refresh_logic_to_orch branch
