### ISSUE TITLE
Introduce a new command line parameter to log services' status

### ISSUE THREAD

**Issue by androklis** [gtrianta1965/ServiceWatcher#17]
This command line option (-log) means that ServiceWatcher will append all services' status to a log file on a daily rotation (e.g. 20170726.log, 20170727.log)

**Comment by gtrianta1965** [comment]
This feature will be implemented using log4j and it will be used for logging/debugging the whole application. We will examine how we can also use log4j for logging services status as well (maybe declaring multiple loggers and appenders). This feature needs careful design.

**Comment by gtrianta1965** [comment]
I close the issue. The feature has been implemented using log4j and -debug command line option.
