### ISSUE TITLE
-conf input bug

### ISSUE THREAD

**Issue by KALALEX** [gtrianta1965/ServiceWatcher#21]
## Correct
άμα δώσω:
sw -conf:peravrexei

Παίρνω (σωστά):
Custom configuration specified (peravrexei)
Error reading configuration (Property file peravrexei does not exist)

Αμα δώσω:
sw -conf:config-ut1.properties

Παίρνω(σωστά):
Custom configuration specified (config-ut1.properties)

## Not-Correct
Αμα δώσω:
sw -conf
Πάιρνω (Δεν μου λέει πιό διάβασε τελικά και συνεχίζει):
Arguments -conf must be followed by a colon (:) and the <config file Name>
Initializing key and initialization vector.

## BUG

Αμα δώσω:
sw -conf:eisai -conf:poli -conf:asxeτοs
Παίρνω (???):
Custom configuration specified (eisai)
Custom configuration specified (poli)
Custom configuration specified (asxetos)
Error reading configuration (Property file asxetos does not exist)

**Comment by androklis** [comment]
Done
