### ISSUE TITLE
-conf doesn't work on windows when full path of configuration file is specified (contains colon which confuses parser)

### ISSUE THREAD

**Issue by gtrianta1965** [gtrianta1965/ServiceWatcher#26]
If you run the command:

sw -conf:c:\00\dbconfig.properties

Then you get the error:
Arguments -conf must be followed by a colon (:) and the <config file Name>
Initializing key and initialization vector.

The program opens but picks up the default configuration

Definetely it has to do with the parsing of ":" of -conf option

**Comment by gtrianta1965** [comment]
Το είχα διορθώσει:

                        //Fix bug with colon in file name (e.g. C:\something\config.properties)
                        //This bug appears only in windows
                        tmp = args[i].toLowerCase().replaceAll("^-conf:", "");

Σχολιάστηκε και αλλάχτηκε σε:
 tmp = (args[i].split(":", 2)[1]).trim();

Υπάρχει κάποια διαφορά? Είδατε ότι δεν δουλεύει το πρώτο?

**Comment by androklis** [comment]
Δουλεύουν και τα 2. Το είχα κάνει εγώ για να δω πως δουλεύει με το να κάνεις reference issue από το commit. Ωστόσο, από command line ότι και να τρέξω παίρνω στο τέλος ": command not found" και δεν το βρήκα πουθενά στον κώδικα.

**Comment by gtrianta1965** [comment]
Τελικά έχουμε κάποιο πρόβλημα με αυτό? Τι γίνεται με το πρόβλημα που σου βγάζει?

**Comment by androklis** [comment]
Μου εκτυπώνει στο τέλος το μήνυμα που έγραψα ": command not found". Εσένα όχι;

**Comment by gtrianta1965** [comment]
Αχ βρε Ανδροκλή!!!

Ο χαρακτήρας : στο Unix/Linux είναι command line terminator. Αυτό σημαίνει ότι μπορείς να εκτελέσεις πολλές εντολές σε μία γραμμή:

ls *.txt : ls *.sh

Στην περίπτωσή σου προσπαθεί να καταλάβει τι εντολή έδωσες μετά το : , πάει να την εκτελέσει (φυσικά δεν υπάρχει) και βγάζει το λάθος!!!


Issue Solved!!!!
