### ISSUE TITLE
When running ServiceWatcher with -nogui command line and we do not specify autorefresh then program should exit after first run

### ISSUE THREAD

**Issue by gtrianta1965** [gtrianta1965/ServiceWatcher#29]
with -nogui ServiceWatcher correctly runs only once but it doesn't exit. The System.exit(0) is missing (CommanfLineRunner.java)

**Maybe it is fixed as I was looking at it in the branch threded_reporter_master_merge**

**Comment by KALALEX** [comment]
Caused by #30 
Fixed by b70843fab07198bd55e7ae8decebfb211eed59d0
branch threded_reporter_master_merge
