### ISSUE TITLE
With reporter running as a thread and -nogui option specified, ServiceWatcher doesn't have a chance to send an email

### ISSUE THREAD

**Issue by gtrianta1965** [gtrianta1965/ServiceWatcher#30]
This is a side effect if we implement #29. 

I am thinking of 2 different approaches:

1. Don't send an email when ServiceWatcher runs once with -nogui
2. Send an email in the same thread (don't create another thread) 

_By the way, Reporter runs OK when -nogui -autorefresh:1 is specified._

**Comment by KALALEX** [comment]
fixed in : b70843fab07198bd55e7ae8decebfb211eed59d0
