### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by androklis** [gtrianta1965/ServiceWatcher#34]
We get a Null Pointer exception error if a service in the configuration file does not have one of the attributes that there are in the table. For example, a service does not belong to a group. So group attribute is not in added in the configuration file for that specific service and the GUI is not initialized properly.

**Comment by androklis** [comment]
The same happens if service type is not one of the required types

**Comment by gtrianta1965** [comment]
Regarding the empty group, I suggest the following: During read (Confuguration.java) of properties per each service, if group is missing or it is empty then add the service to the generic group with description "NoGroup".
Something like this:

serviceParameter.setDescription(prop.getProperty("description." + i) == null ? "No Description" : prop.getProperty("description." + i));

Maybe we have to do something more clever regarding null and empty ("") values.

**Comment by gtrianta1965** [comment]
Even better if we do this in ServiceParameter.java, in the setter methods!!!
